USE SalesDW;
GO

SELECT
    ROW_NUMBER() OVER (ORDER BY PRD.PRODUCT_ID) AS PRODUCT_KEY,
    PRD.PRODUCT_ID,
    PRD.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    BR.BRAND_NAME,
    PRD.MODEL_YEAR,
    PRD.LIST_PRICE AS UNIT_PRICE
INTO Gold.dim_products
FROM Silver.products AS PRD
LEFT JOIN Silver.categories AS CAT
    ON PRD.CATEGORY_ID = CAT.CATEGORY_ID
LEFT JOIN Silver.brands AS BR
    ON PRD.BRAND_ID = BR.BRAND_ID;