use SalesDW;
go

SELECT
    ROW_NUMBER() OVER (ORDER BY STAFF.STAFF_ID) AS STAFF_KEY,
    STAFF.STAFF_ID,
    STAFF.FULL_NAME,
    STAFF.EMAIL,
    STAFF.ACTIVE AS IS_ACTIVE,
    STORE.STORE_NAME,
    STAFF.MANAGER_ID
INTO Gold.dim_staffs
FROM Silver.staffs AS STAFF
LEFT JOIN Silver.stores AS STORE
    ON STAFF.STORE_ID = STORE.STORE_ID;
